project:
  type: website

website:
  title: "DSCI 310 Review"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
        
      - section: "Basics"
        contents:
          - href: intro_to_git.qmd
            text: "Git Commands"
          - href: git_concepts.qmd
            text: "Git Concepts"
          - href: bash_scripts.qmd
            text: "Bash Scripts"
            
      - section: "General"
        contents: 
          - href: environments.qmd
            text: "Environments"
          - href: docker.qmd
            text: "Docker Containers"
          - href: github_actions.qmd
            text: "GitHub Actions"
          - href: ci_cd.qmd
            text: "CI & CD"
          - href: makefiles.qmd
            text: "Makefiles"
            
      - section: "Quarto"
        contents: 
          - href: quarto_docs.qmd
            text: "Quarto Reports"
          - href: making_websites.qmd
            text: "Quarto Websites"
            
      - section: "Packages"
        contents:
          - href: making_a_package.qmd
            text: "Making an R Package"
          - href: functions.qmd
            text: "Functions"
          - href: tests.qmd
            text: "Testing"
          - href: validation.qmd
            text: "Validation"
          - href: dependencies.qmd
            text: "Dependencies"
          - href: supporting.qmd
            text: "Badges, Licenses & More"

format:
  html:
    code-copy: true
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
