project:
  type: website

website:
  title: "DSCI 310 Review"
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
        
      - section: "Basics"
        contents:
          - href: pages/intro_to_git.qmd
            text: "Git Commands"
          - href: pages/git_concepts.qmd
            text: "Git Concepts"
          - href: pages/bash_scripts.qmd
            text: "Bash Scripts"
            
      - section: "General"
        contents: 
          - href: pages/environments.qmd
            text: "Environments"
          - href: pages/docker.qmd
            text: "Docker Containers"
          - href: pages/github_actions.qmd
            text: "GitHub Actions (CI&CD)"
          - href: pages/makefiles.qmd
            text: "Makefiles"
            
      - section: "Quarto"
        contents: 
          - href: pages/markdown.qmd
            name: "Markdown Tips"
          - href: pages/quarto_docs.qmd
            text: "Quarto Reports"
          - href: pages/making_websites.qmd
            text: "Quarto Websites"
            
      - section: "Packages"
        contents:
          - href: pages/making_a_package.qmd
            text: "Making an R Package"
          - href: pages/functions.qmd
            text: "Functions"
          - href: pages/tests.qmd
            text: "Testing"
          - href: pages/validation.qmd
            text: "Validation"
          - href: pages/dependencies.qmd
            text: "Dependencies"
          - href: pages/supporting.qmd
            text: "Badges, Licenses & More"

format:
  html:
    code-copy: true
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true
