project:
  type: website

website:
  title: "Final Exam Review"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Basics"
        contents:
          - href: intro_to_git.qmd
            text: "Git Commands"
          - href: git_concepts.qmd
            text: "Git Concepts"
          - href: bash_scripts.qmd
            text: "Bash Scripts"
      - section: "General"
        contents: 
          - href: environments.qmd
            text: "Environments"
          - href: docker.qmd
            text: "Docker Containers"
          - href: github_actions.qmd
            text: "GitHub Actions"
      - section: "Quarto"
        contents: 
          - href: quarto_docs.qmd
            text: "Reproducible Quarto Docs"
          - href: making_websites.qmd
            text: "Websites With Quarto"
      - section: "Packages"
        contents:
          - functions.qmd
          - tests.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
