project:
  type: website

website:
  title: "Final Exam Review"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: making_websites.qmd
        text: Making Websites With Quarto
      - href: about.qmd
        text: Not Sure Yet

website:
  title: "Final Exam Review"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Basics"
        contents:
          - href: intro_to_git.qmd
            text: Intro to Git Commands
          - making_websites.qmd
      - section: "Packages"
        contents:
          - functions.qmd
          - tests.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



