---
title: "Making Websites With Quarto"
format: html
---

## Website "Bones"

Start with:

```
quarto create
```

* Select `project` > `website` > Directory: `/` > Title: `Final Review`

Alternatively, create the following files:

* `_quarto.yml`
* `index.qmd`
* `<project_name>.Rproj`
* `styles.css` (not necessary)
* other `.qmd` files (not necessary)
* Add files to `.gitignore`

## 3 Main Locations with GitHub Pages for Rendering

1. `/(root)`: You are ready simply by doing:

```
quarto render index.qmd
```

This will make an `index.html` file that git will look for. If you do not have a index.html file in your root folder, it will instead display your `README.md`!

Push all changes to the (main branch) repo, and select the right option in Settings > Pages > Build and deployment > Branch .

2. `docs/`: There are a few tasks necessary:

* Ensure `docs/` is not blocked in the `.gitignore` file
* Set `output-dir: docs` under project: type: in `_quarto.yml`

3. `gh-pages` branch:

* Delete any `docs/` folder and block in the `.gitignore` file